# Advance` Numpy` PART 2 [Numpy webseit](https://numpy.org/doc/1.26/user/absolute_beginners.html)

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
empty = np.empty((2))
print(empty)

print(empty[1])

[2.84674330e-123 4.00599039e+063]
4.005990386577703e+63


In [5]:
empty = np.empty((2, 3))
print(empty)
print("------------")
print(empty[1])

[[-1.02566090e-311  1.16850104e+177  1.02567146e-311]
 [ 1.02567146e-311  9.88131292e-323  2.47032823e-322]]
------------
[1.02567146e-311 9.88131292e-323 2.47032823e-322]


In [6]:
empty = np.empty((2, 4)) # 2 rows 4 col
print(empty)

print(empty[0])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[0. 0. 0. 0.]


In [7]:
empty = np.empty((2, 4))
print(empty)
print("------------")
print(empty[1])

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
------------
[0. 0. 0. 0.]


In [8]:
x = np.arange(23)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [9]:
even = np.arange(0,23,2) # print 0 to 23 , 2 means even number
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [10]:
odd = np.arange(1, 27, 3) 
odd

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25])

In [11]:
diff = np.arange(0,23,4)
diff

array([ 0,  4,  8, 12, 16, 20])

In [12]:
diff = np.arange(0,23,0.515) # 1 st number second number and last number called step size
diff

array([ 0.   ,  0.515,  1.03 ,  1.545,  2.06 ,  2.575,  3.09 ,  3.605,
        4.12 ,  4.635,  5.15 ,  5.665,  6.18 ,  6.695,  7.21 ,  7.725,
        8.24 ,  8.755,  9.27 ,  9.785, 10.3  , 10.815, 11.33 , 11.845,
       12.36 , 12.875, 13.39 , 13.905, 14.42 , 14.935, 15.45 , 15.965,
       16.48 , 16.995, 17.51 , 18.025, 18.54 , 19.055, 19.57 , 20.085,
       20.6  , 21.115, 21.63 , 22.145, 22.66 ])

# `Linspace` Called linear space

In [13]:
lin = np.linspace(0,20, num=10) # give us only 10 number
lin

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [14]:
lin = np.linspace(0,10, num=5)  # give us only 5 number
lin

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [15]:
lin = np.linspace(0, -10, num=15)
lin

array([  0.        ,  -0.71428571,  -1.42857143,  -2.14285714,
        -2.85714286,  -3.57142857,  -4.28571429,  -5.        ,
        -5.71428571,  -6.42857143,  -7.14285714,  -7.85714286,
        -8.57142857,  -9.28571429, -10.        ])

In [16]:
lin = np.linspace(0, 20, num=3)
lin

array([ 0., 10., 20.])

In [17]:
lin = np.linspace(0, 10, num=1)
lin

array([0.])

In [18]:
lin = np.linspace(0, 10, num=170)
lin

array([ 0.        ,  0.0591716 ,  0.1183432 ,  0.17751479,  0.23668639,
        0.29585799,  0.35502959,  0.41420118,  0.47337278,  0.53254438,
        0.59171598,  0.65088757,  0.71005917,  0.76923077,  0.82840237,
        0.88757396,  0.94674556,  1.00591716,  1.06508876,  1.12426036,
        1.18343195,  1.24260355,  1.30177515,  1.36094675,  1.42011834,
        1.47928994,  1.53846154,  1.59763314,  1.65680473,  1.71597633,
        1.77514793,  1.83431953,  1.89349112,  1.95266272,  2.01183432,
        2.07100592,  2.13017751,  2.18934911,  2.24852071,  2.30769231,
        2.36686391,  2.4260355 ,  2.4852071 ,  2.5443787 ,  2.6035503 ,
        2.66272189,  2.72189349,  2.78106509,  2.84023669,  2.89940828,
        2.95857988,  3.01775148,  3.07692308,  3.13609467,  3.19526627,
        3.25443787,  3.31360947,  3.37278107,  3.43195266,  3.49112426,
        3.55029586,  3.60946746,  3.66863905,  3.72781065,  3.78698225,
        3.84615385,  3.90532544,  3.96449704,  4.02366864,  4.08

In [19]:
lin.dtype

dtype('float64')

In [20]:
# define the dtype of array
x = np.arange(0 ,22.6, 1.5, dtype=np.int8)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
      dtype=int8)

In [21]:
lin=np.ones(2,dtype=np.float64)
lin

array([1., 1.])

In [22]:
lin=np.arange(2,dtype=np.float64)
lin

array([0., 1.])

In [23]:
lin=np.arange(22.6,dtype=np.float64)
lin

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22.])

# Sort arrays

In [24]:
# sorting an array
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [25]:
arr=np.sort(arr)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
x = np.array([3,1,2])
np.argsort(x)

array([1, 2, 0], dtype=int64)

In [27]:
x = np.array([[0,3],[0,2]])
x

array([[0, 3],
       [0, 2]])

In [28]:
ind = np.argsort(x,axis=0) # sort along first axis (down)
ind

array([[0, 1],
       [1, 0]], dtype=int64)

In [29]:
np.take_along_axis(x,ind,axis=0) 

array([[0, 2],
       [0, 3]])

# concatenate these arrays in `nd`

In [30]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.concatenate((a,b))
c


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
x = np.array([[1,2],[3,4]]) # 2x2 array
y=np.array([[5,6]]) # 1x2 array , making 3 rows 2 col
z = np.concatenate((x,y),axis=0)# axis = o means add rows
z


array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
w = np.array([[2,3],[3,4]]) # 2x2 array now Concatenate 2x2 values x have 2x2
z = np.concatenate((x,w),axis=1) # axis = 1 means add columns
z

array([[1, 2, 2, 3],
       [3, 4, 3, 4]])

In [33]:
x.ndim

2

In [34]:
y.ndim

2

# create a 3`D array`

In [35]:
# create a 3D array
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [36]:
# create a 3D array
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim

3

In [37]:
array_example.size

24

In [38]:
len(array_example)

3

In [39]:
array_example.dtype

dtype('int32')

In [40]:
array_example.shape # 3d , 2 rows each array  , 4 col

(3, 2, 4)

In [41]:
# creata 3D array of size (3,1,4)
a1 = np.array([[[0, 1, 2, 3]],
                          [[4, 5, 6, 7]],
                          [[0, 1, 2, 3]]])
a1.shape

(3, 1, 4)

In [42]:
a1.ndim

3

# reshape the `a `

In [43]:
# reshape the a 
a2 = a1.reshape(6,2) # 6 rows 2 col
a2.shape

(6, 2)

In [44]:
a1

array([[[0, 1, 2, 3]],

       [[4, 5, 6, 7]],

       [[0, 1, 2, 3]]])

In [45]:
a2 # a1 convert a2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [0, 1],
       [2, 3]])

In [46]:
a2.reshape(3,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

In [47]:
a2.reshape(3,1,4) # 4 col

array([[[0, 1, 2, 3]],

       [[4, 5, 6, 7]],

       [[0, 1, 2, 3]]])

# create a `1D `array

In [48]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a.shape

(8,)

In [49]:
a[np.newaxis, :].shape

(1, 8)

# convert that into `2D `array

In [50]:
# convert that into 2D array
b = a[np.newaxis, :]
b.shape
b

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [51]:
c = a[: , np.newaxis]
c.shape
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [52]:
b = a[np.newaxis, :] # 8 rows 1 col 
b.shape

(1, 8)

In [53]:
c = a[: , np.newaxis]# 1 rows 8 col 
c.shape

(8, 1)

# indexing and slicing

In [54]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
a[3]

4

In [56]:
a[2:5]

array([3, 4, 5])

In [57]:
a[-4:-2]

array([5, 6])

In [58]:
a[1:]

array([2, 3, 4, 5, 6, 7, 8])

In [59]:
a[0:]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [60]:
a[-2:]

array([7, 8])

In [61]:
b = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
b[2]

array([ 9, 10, 11, 12])

In [63]:
b[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [64]:
b[b<5]

array([1, 2, 3, 4])

In [65]:
b[b <= 10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
b[b % 2 == 0] # filter even numbers

array([ 2,  4,  6,  8, 10, 12])

In [67]:
# filter odd numbers
b[b % 2 == 1] 

array([ 1,  3,  5,  7,  9, 11])

In [68]:
# use two conditions & sign
b[(b > 2) & (b < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
# use three conditions and filter the arrays
b[(b > 2) & (b < 11) & (b % 2 == 0)]

array([ 4,  6,  8, 10])

In [70]:
b[(b > 2) | (b < 11)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])