# Numpy Introduction [Numpy webseit](https://numpy.org/doc/1.26/user/absolute_beginners.html)

In [2]:
pip install numpy

In [3]:
import numpy as np

In [4]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [5]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

# 1d Array

In [6]:
a = np.arange(6)
print(a)
a.shape # here just 6 vales not row column

[0 1 2 3 4 5]


(6,)

# 2d Array

In [7]:
a2 =a [np.newaxis,:]
print(a2)
a2.shape # 1 row 6 column

[[0 1 2 3 4 5]]


(1, 6)

In [8]:
a2 =a [:,np.newaxis]
print(a2)
a2.shape # 6 row 1 column

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


(6, 1)

In [9]:
a2.shape

(6, 1)

# 3d Array

In [10]:
a3 = a2 [np.newaxis,:]
print(a2)
a3.shape # 1 row 6 column and 1 third axis

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


(1, 6, 1)

# Creating Arrays with Numpy

In [46]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
b = np.array([(1, 2, 3, 4, 5, 6, 7), (4, 5, 6, 7, 8, 9, 10)])
c = a,b
c


(array([1, 2, 3, 4, 5, 6, 7]),
 array([[ 1,  2,  3,  4,  5,  6,  7],
        [ 4,  5,  6,  7,  8,  9, 10]]))

In [12]:
a.dtype # data type of array element

dtype('int32')

In [13]:
type(a) # type of array, nd means n/1 dimentional array 

numpy.ndarray

In [47]:
type(b)

numpy.ndarray

In [14]:
b.dtype

dtype('int32')

In [15]:
print(a)
a.shape

[1 2 3 4 5 6 7]


(7,)

In [16]:
print(b)
b.shape

[[ 1  2  3  4  5  6  7]
 [ 4  5  6  7  8  9 10]]


(2, 7)

# initialize arrays `zeroes Array`

In [17]:
zeroes= np.zeros((3,4)) # 3 rows , $ columns  , 3 by 4 2d array
zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
zeroes.dtype

dtype('float64')

In [19]:
ones= np.ones((5,4)) # 5 rows , 4 columns  , 3 by 4 2d array
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [21]:
full =np.full((2,5),7)  # 2 rows , 5 columns , where the value just 7 exist
full

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

# Creating an `Identity Matrix`


In [22]:
identity =np.eye((5))
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
identity.dtype

dtype('float64')

# array attributes

# how we can check `nd` or `2d`?

In [24]:
a.shape

(7,)

In [25]:
b.shape

(2, 7)

# How many Elements?

In [26]:
len(a)

7

In [27]:
len(b)

2

# How we can check `Dimentional`?

In [28]:
a.ndim

1

In [29]:
b.ndim

2

In [30]:
identity.ndim

2

# How check the `Size`

In [31]:
#  gibe us the number of elements
a.size

7

In [32]:
b.size

14

# Basic operations

In [33]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [34]:
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8,  9, 10]])

In [35]:
c = a - b 
c

array([[ 0,  0,  0,  0,  0,  0,  0],
       [-3, -3, -3, -3, -3, -3, -3]])

In [36]:
d = b - a
d

array([[0, 0, 0, 0, 0, 0, 0],
       [3, 3, 3, 3, 3, 3, 3]])

In [37]:
s = a + b
s

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

# Another Method

In [38]:
r = np.add(a,b)
r

array([[ 2,  4,  6,  8, 10, 12, 14],
       [ 5,  7,  9, 11, 13, 15, 17]])

In [39]:
i = a * b
i

array([[ 1,  4,  9, 16, 25, 36, 49],
       [ 4, 10, 18, 28, 40, 54, 70]])

In [40]:
j = a/b
j

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        ],
       [0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ,
        0.66666667, 0.7       ]])

# Square each element

In [41]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [42]:
k = a ** 2
k

array([ 1,  4,  9, 16, 25, 36, 49])

In [43]:
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8,  9, 10]])

In [44]:
g = b ** 2
g

array([[  1,   4,   9,  16,  25,  36,  49],
       [ 16,  25,  36,  49,  64,  81, 100]])